//
//  MyDatabase.swift
//  Ripple_SwiftUI
//
//  Created by justin frazer on 10/25/19.
//  Copyright © 2019 justin frazer. All rights reserved.
//

import Foundation
import UIKit

class myDataBase {
    
    static var allCharities = [
        //Education - Early Childhood Programs and Services (1.1)
        Charity(id: 1, charityName: "Spread the Word Nevada", profilePhoto: #imageLiteral(resourceName: "Logo"), backgroundPhoto: #imageLiteral(resourceName: "Banner Image"), cause: 1, subCategory: 1, isVerified: true, address: "1065 American Pacific Drive, Henderson, NV", zipCode: 89074),
        Charity(id: 2, charityName: "Readworks", profilePhoto: #imageLiteral(resourceName: "ReadWorks Logo"), backgroundPhoto: #imageLiteral(resourceName: "ReadWorks Banner Image"), cause: 1, subCategory: 1, isVerified: true, address: "", zipCode: 0),
        Charity(id: 3, charityName: "Ferst Readers", profilePhoto: #imageLiteral(resourceName: "FerstReaders Logo"), backgroundPhoto: #imageLiteral(resourceName: "FerstReaders Banner"), cause: 1, subCategory: 1, isVerified: true, address: "", zipCode: 0),
        Charity(id: 4, charityName: "Opportunity, Inc.", profilePhoto: #imageLiteral(resourceName: "Opportunity Logo"), backgroundPhoto: #imageLiteral(resourceName: "Opportunity Banner"), cause: 1, subCategory: 1, isVerified: true, address: "200 E. Cramer Street, Fort Atkinson, WI", zipCode: 53538),
        Charity(id: 5, charityName: "Barbara Bush Foundation", profilePhoto: #imageLiteral(resourceName: "Barbara Bush Logo"), backgroundPhoto: #imageLiteral(resourceName: "Barbara Bush Banner"), cause: 1, subCategory: 1, isVerified: true, address: "516 North Adams Street, Tallahassee, FL", zipCode: 32301),
        
        //Education - Scholarship and Financial Support (1.2)
        Charity(id: 6, charityName: "Children's Scholarship Fund Philadelphia", profilePhoto: #imageLiteral(resourceName: "Childrens Scholarship Fund Logo"), backgroundPhoto: #imageLiteral(resourceName: "Children's Scholarship Fund Banner"), cause: 1, subCategory: 2, isVerified: true, address: "100 SOUTH BROAD STREET, PHILADELPHIA, PA", zipCode: 19110),
        Charity(id: 7, charityName: "Seeds of Hope Charitable Trust", profilePhoto: #imageLiteral(resourceName: "Seeds of Hope Logo"), backgroundPhoto: #imageLiteral(resourceName: "Seeds of Hope Banner"), cause: 1, subCategory: 2, isVerified: true, address: "1300 South Steele St, Denver, CO", zipCode: 80210),
        Charity(id: 8, charityName: "Folds of Honor", profilePhoto: #imageLiteral(resourceName: "Folds of Honor Logo"), backgroundPhoto: #imageLiteral(resourceName: "Folds of Honor Banner"), cause: 1, subCategory: 2, isVerified: true, address: "5800 N Patriot Dr, Owasso, OK", zipCode: 74055),
        Charity(id: 9, charityName: "Step Up For Students", profilePhoto: #imageLiteral(resourceName: "Step up For Students Logo"), backgroundPhoto: #imageLiteral(resourceName: "Step Up for Students Banner"), cause: 1, subCategory: 2, isVerified: true, address: "4655 Salisbury Rd, Jacksonville, FL", zipCode: 32256),
        Charity(id: 10, charityName: "I Know I Can", profilePhoto: #imageLiteral(resourceName: "I Know i Can Logo"), backgroundPhoto: #imageLiteral(resourceName: "I Know i Can Banner"), cause: 1, subCategory: 2, isVerified: true, address: "1108 City Park Ave, Columbus, OH", zipCode: 43206),
        
        //Education - Special Education (1.3)
        Charity(id: 11, charityName: "Little Light House", profilePhoto: #imageLiteral(resourceName: "Little Lighthouse Logo"), backgroundPhoto: #imageLiteral(resourceName: "Little Lighthouse Banner"), cause: 1, subCategory: 3, isVerified: true, address: "5120 E 36th St, Tulsa, OK", zipCode: 74135),
        Charity(id: 12, charityName: "Eye to Eye", profilePhoto: #imageLiteral(resourceName: "Eye to Eye Logo"), backgroundPhoto: #imageLiteral(resourceName: "Eye to Eye Banner"), cause: 1, subCategory: 3, isVerified: true, address: "2001 Center St, Berkeley, CA", zipCode: 94704),
        Charity(id: 13, charityName: "Visually Impaired Preschool Services", profilePhoto: #imageLiteral(resourceName: "VIPS Logo"), backgroundPhoto: #imageLiteral(resourceName: "VIPS Banner"), cause: 1, subCategory: 3, isVerified: true, address: "1100 West 42nd St, Indianapolis, IN", zipCode: 46208),
        Charity(id: 14, charityName: "Blind Children's Learning Center", profilePhoto: #imageLiteral(resourceName: "Blind Children's Learning Center Logo"), backgroundPhoto: #imageLiteral(resourceName: "Blind Children's Learning Center Banner"), cause: 1, subCategory: 3, isVerified: true, address: "18542-B VANDERLIP AVE, SANTA ANA, CA", zipCode: 92075),
        Charity(id: 15, charityName: "National Center for Learning Disabilities", profilePhoto: #imageLiteral(resourceName: "National Pediatric Cancer Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "National Center for Learning Disabilities Banner"), cause: 1, subCategory: 3, isVerified: true, address: "32 Laight St, New York, NY", zipCode: 10013),
        
        //Education - Adult Education Programs and Services (1.4)
        Charity(id: 16, charityName: "The Education Foundation of Collier County", profilePhoto: #imageLiteral(resourceName: "Education Foundation of Collier County Logo"), backgroundPhoto: #imageLiteral(resourceName: "Education Foundation of Collier County Banner"), cause: 1, subCategory: 4, isVerified: true, address: "3606 Enterprise Ave, Naples, FL", zipCode: 34104),
        Charity(id: 17, charityName: "The Chicago Public Education Fund", profilePhoto: #imageLiteral(resourceName: "Chicago Public Education Fund Logo"), backgroundPhoto: #imageLiteral(resourceName: "Chicago Public Education Fund Banner"), cause: 1, subCategory: 4, isVerified: true, address: "200 W Adams St, Chicago, IL ", zipCode: 60606),
        Charity(id: 18, charityName: "Mercy Learning Center of Bridgeport", profilePhoto: #imageLiteral(resourceName: "Mercy Learning Center Logo"), backgroundPhoto: #imageLiteral(resourceName: "Mercy Learning Center Banner"), cause: 1, subCategory: 4, isVerified: true, address: "637 Park Ave, Bridgeport, CT", zipCode: 06604),
        Charity(id: 19, charityName: "Operation HOPE", profilePhoto: #imageLiteral(resourceName: "Operation HOPE Logo"), backgroundPhoto: #imageLiteral(resourceName: "Operation HOPE Banner"), cause: 1, subCategory: 4, isVerified: true, address: "8910 Two Notch Road Columbia, SC", zipCode: 29223),
        Charity(id: 20, charityName: "Society of Classical Studies", profilePhoto: #imageLiteral(resourceName: "Society for Classical Studies Logo"), backgroundPhoto: #imageLiteral(resourceName: "Society for Classical Studies Banner"), cause: 1, subCategory: 4, isVerified: true, address: "20 Cooper Square, New York, NY ", zipCode: 10003),
        
        //Education - Youth Education Programs and Services (1.5)
        Charity(id: 21, charityName: "Sponsors for Educational Opportunity", profilePhoto: #imageLiteral(resourceName: "SEO Logo"), backgroundPhoto: #imageLiteral(resourceName: "SEO Banner"), cause: 1, subCategory: 5, isVerified: true, address: "55 Exchange Place, New York, NY", zipCode: 10005),
        Charity(id: 22, charityName: "Pratham USA", profilePhoto: #imageLiteral(resourceName: "Pratham Logo"), backgroundPhoto: #imageLiteral(resourceName: "Pratham Banner"), cause: 1, subCategory: 5, isVerified: true, address: "9703 Richmond Ave, Houston, TX", zipCode: 77042),
        Charity(id: 23, charityName: "Wilderness Inquiry", profilePhoto: #imageLiteral(resourceName: "Wilderness Inquiry Logo"), backgroundPhoto: #imageLiteral(resourceName: "Wilderness Inquiry Banner"), cause: 1, subCategory: 5, isVerified: true, address: "808 14th Ave SE, Minneapolis, MN", zipCode: 55414),
        Charity(id: 24, charityName: "Center for Creative Education", profilePhoto: #imageLiteral(resourceName: "Center for Creative Education Logo"), backgroundPhoto: #imageLiteral(resourceName: "Center for Creative Education Banner"), cause: 1, subCategory: 5, isVerified: true, address: "425 24th Street West Palm Beach, FL", zipCode: 33407),
        Charity(id: 25, charityName: "Street School", profilePhoto: #imageLiteral(resourceName: "Street School Logo"), backgroundPhoto: #imageLiteral(resourceName: "Street School Banner"), cause: 1, subCategory: 5, isVerified: true, address: "1135 S. Yale Avenue, Tulsa, OK", zipCode: 74112),
        
        //Education - Educations Policy and Reform (1.6)
        Charity(id: 26, charityName: "The Parent-Child Home Program", profilePhoto: #imageLiteral(resourceName: "Parent Child Home Program Logo"), backgroundPhoto: #imageLiteral(resourceName: "Parent Child Home Program Banner"), cause: 2, subCategory: 1, isVerified: true, address: "163B Mineola Boulevard Mineola, NY", zipCode: 11501),
        Charity(id: 27, charityName: "San Francisco Education Fund", profilePhoto: #imageLiteral(resourceName: "San Francisco Education Fund Logo"), backgroundPhoto: #imageLiteral(resourceName: "San Francisco Education Fund Banner"), cause: 2, subCategory: 1, isVerified: true, address: "2730 Bryant Street, San Francisco, CA", zipCode: 94110),
        Charity(id: 28, charityName: "Intercollegiate Studies Institute", profilePhoto: #imageLiteral(resourceName: "Intercollegiate Studies Institute Logo"), backgroundPhoto: #imageLiteral(resourceName: "Intercollegiate Studies Institute Banner"), cause: 2, subCategory: 1, isVerified: true, address: "3901 Centerville Road, Wilmington, DE", zipCode: 19807),
        Charity(id: 29, charityName: "The NEA Foundation", profilePhoto: #imageLiteral(resourceName: "the NEA Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "The NEA Foundation Banner"), cause: 2, subCategory: 1, isVerified: true, address: "1201 16th Street, NW Washington, DC", zipCode: 20036),
        Charity(id: 30, charityName: "New Visions for Public Schools", profilePhoto: #imageLiteral(resourceName: "New Visions for Public Schools Logo"), backgroundPhoto: #imageLiteral(resourceName: "New Visions for Public Schools Banner"), cause: 2, subCategory: 1, isVerified: true, address: "205 East 42nd Street, New York, NY", zipCode: 10017),
        
        //Environment - Environmental Protection & Conservation (2.1)
        Charity(id: 31, charityName: "Amazon Conservation Association", profilePhoto: #imageLiteral(resourceName: "Amazon Conservation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Amazon Conservation Banner"), cause: 2, subCategory: 1, isVerified: true, address: "1012 14th Street NW, Washington, DC", zipCode: 20005),
        Charity(id: 32, charityName: "Appalachian Voices", profilePhoto: #imageLiteral(resourceName: "Appalachian Voices Logo"), backgroundPhoto: #imageLiteral(resourceName: "Appalachian Voices Banner"), cause: 2, subCategory: 1, isVerified: true, address: "589 West King Street Boone, NC", zipCode: 28607),
        Charity(id: 33, charityName: "Chattahoochee Riverkeeper", profilePhoto: #imageLiteral(resourceName: "Chattahoochee Riverkeeper Logo"), backgroundPhoto: #imageLiteral(resourceName: "Chattahoochee Riverkeeper Banner"), cause: 2, subCategory: 1, isVerified: true, address: "916 Joseph E. Lowery Blvd. NW Atlanta, GA", zipCode: 30318),
        Charity(id: 34, charityName: "Environmental & Energy Study Institute", profilePhoto: #imageLiteral(resourceName: "Environmental and Energy Study Institute Logo"), backgroundPhoto: #imageLiteral(resourceName: "Environmental and Energy Study Institute Banner"), cause: 2, subCategory: 1, isVerified: true, address: "1020 19th Street, Washington, DC ", zipCode: 20036),
        Charity(id: 35, charityName: "PATH Foundation", profilePhoto: #imageLiteral(resourceName: "PATH Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "PATH Foundation Banner"), cause: 2, subCategory: 1, isVerified: true, address: "", zipCode: 0),
        
        //Environment - Botanical Gardens, Parks, & Nature Centers (2.2)
        Charity(id: 36, charityName: "New York-New Jersey Trail Conference", profilePhoto: #imageLiteral(resourceName: "New York-New Jersey Trail Conference Logo"), backgroundPhoto: #imageLiteral(resourceName: "New York-New Jersey Trail Conference Banner"), cause: 2, subCategory: 2, isVerified: true, address: "600 Ramapo Valley Rd Mahwah, NJ", zipCode: 07430),
        Charity(id: 37, charityName: "Grand Teton National Park Foundation", profilePhoto: #imageLiteral(resourceName: "Grand Teton National Park Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Grand Teton National Park Foundation Banner"), cause: 2, subCategory: 2, isVerified: true, address: "115 E Pearl Ave, Jackson, WY", zipCode: 83001),
        Charity(id: 38, charityName: "Hidden Villa", profilePhoto: #imageLiteral(resourceName: "Hidden Villa Logo"), backgroundPhoto: #imageLiteral(resourceName: "Hidden Villa Banner"), cause: 2, subCategory: 2, isVerified: true, address: "6870 Moody Rd, Los Altos Hills, CA", zipCode: 94022),
        Charity(id: 39, charityName: "Seattle Parks Foundation", profilePhoto: #imageLiteral(resourceName: "Seattle Parks Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Seattle Parks Foundation Banner"), cause: 2, subCategory: 2, isVerified: true, address: "105 S Main St, Seattle, WA", zipCode: 98104),
        Charity(id: 40, charityName: "Friends of Acadia", profilePhoto: #imageLiteral(resourceName: "Friends of Acadia Logo"), backgroundPhoto: #imageLiteral(resourceName: "Friends of Acadia Banner"), cause: 2, subCategory: 2, isVerified: true, address: "43 Cottage St D, Bar Harbor, ME", zipCode: 04609),
        
        // Health - Diseases, Disorders, & Disciplines (3.1)
        Charity(id: 41, charityName: "The Cornelia de Lange Syndrome Foundation", profilePhoto: #imageLiteral(resourceName: "The Cornelia de Lange Syndrome Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Cornelia de Lange Syndrome Foundation Banner"), cause: 3, subCategory: 1, isVerified: true, address: "302 West Main Street, Avon, CT", zipCode: 06001),
        Charity(id: 42, charityName: "Cystic Fibrosis Research, Inc.", profilePhoto: #imageLiteral(resourceName: "Cystic Fibrosis Research, Inc. Logo"), backgroundPhoto: #imageLiteral(resourceName: "Cystic Fibrosis Research, Inc. Banner"), cause: 3, subCategory: 1, isVerified: true, address: "1731 Embarcadero Road, Palo Alto, CA", zipCode: 94303),
        Charity(id: 43, charityName: "GBS|CIDP Foundation International", profilePhoto: #imageLiteral(resourceName: "GBS|CIDP Foundation International Logo"), backgroundPhoto: #imageLiteral(resourceName: "GBS|CIDP Foundation International Banner"), cause: 3, subCategory: 1, isVerified: true, address: "375 East Elm Street, Conshohocken, PA", zipCode: 19428),
        Charity(id: 44, charityName: "The Myositis Association", profilePhoto: #imageLiteral(resourceName: "The Myositis Association Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Myositis Association Banner"), cause: 3, subCategory: 1, isVerified: true, address: "1940 Duke St, Alexandria, VA", zipCode: 22314),
        Charity(id: 45, charityName: "American Autoimmune Related Diseases Association", profilePhoto: #imageLiteral(resourceName: "American Autoimmune Related Diseases Association Logo"), backgroundPhoto: #imageLiteral(resourceName: "American Autoimmune Related Diseases Association Banner"), cause: 3, subCategory: 1, isVerified: true, address: "22100 Gratiot Ave, Eastpointe, MI", zipCode: 48021),
        
        // Health - Patient & Family Support (3.2)
        Charity(id: 46, charityName: "Sharsheret", profilePhoto: #imageLiteral(resourceName: "Sharsheret Logo"), backgroundPhoto: #imageLiteral(resourceName: "Sharsheret Banner"), cause: 3, subCategory: 2, isVerified: true, address: "1631 Pontius Ave, Los Angeles, California", zipCode: 90025),
        Charity(id: 47, charityName: "Ronald McDonald House Charities of Eastern Wisconsin", profilePhoto: #imageLiteral(resourceName: "Ronald McDonald House Charities of Eastern Wisconsin Logo"), backgroundPhoto: #imageLiteral(resourceName: "Ronald McDonald House Charities of Eastern Wisconsin Banner"), cause: 3, subCategory: 2, isVerified: true, address: "8948 W Watertown Plank Rd, Wauwatosa, WI", zipCode: 53226),
        Charity(id: 48, charityName: "Give Kids The World", profilePhoto: #imageLiteral(resourceName: "Give Kids The World Logo"), backgroundPhoto: #imageLiteral(resourceName: "Give Kids The World Banner"), cause: 3, subCategory: 2, isVerified: true, address: "210 S Bass Rd, Kissimmee, FL", zipCode: 34746),
        Charity(id: 49, charityName: "HopeKids", profilePhoto: #imageLiteral(resourceName: "HopeKids Logo"), backgroundPhoto: #imageLiteral(resourceName: "HopeKids Banner"), cause: 3, subCategory: 2, isVerified: true, address: "", zipCode: 0),
        Charity(id: 50, charityName: "National Organization for Rare Disorders", profilePhoto: #imageLiteral(resourceName: "National Organization for Rare Disorders Logo"), backgroundPhoto: #imageLiteral(resourceName: "National Organization for Rare Disorders Banner"), cause: 3, subCategory: 2, isVerified: true, address: "55 Kenosia Avenue Danbury, CT", zipCode: 06810),
        
        // Health - Treatment & Prevention Services (3.3)
        Charity(id: 51, charityName: "Community Volunteers in Medicine", profilePhoto: #imageLiteral(resourceName: "Community Volunteers in Medicine Logo"), backgroundPhoto: #imageLiteral(resourceName: "Community Volunteers in Medicine Banner"), cause: 3, subCategory: 3, isVerified: true, address: "300 Lawrence Dr, West Chester, PA", zipCode: 19380),
        Charity(id: 52, charityName: "Sankara Eye Foundation, USA", profilePhoto: #imageLiteral(resourceName: "Sankara Eye Foundation, USA Logo"), backgroundPhoto: #imageLiteral(resourceName: "Sankara Eye Foundation, USA Banner"), cause: 3, subCategory: 3, isVerified: true, address: "1900 McCarthy Blvd, Milpitas, CA", zipCode: 95035),
        Charity(id: 53, charityName: "La Comunidad Hispana (LCH)", profilePhoto: #imageLiteral(resourceName: "La Comunidad Hispana (LCH) Logo"), backgroundPhoto: #imageLiteral(resourceName: "La Comunidad Hispana (LCH) Banner"), cause: 3, subCategory: 3, isVerified: true, address: "731 W Cypress St, Kennett Square, PA", zipCode: 19348),
        Charity(id: 54, charityName: "St. Petersburg Free Clinic", profilePhoto: #imageLiteral(resourceName: "St. Petersburg Free Clinic Logo"), backgroundPhoto: #imageLiteral(resourceName: "St. Petersburg Free Clinic Banner"), cause: 3, subCategory: 3, isVerified: true, address: "863 3rd Ave N, St. Petersburg, FL", zipCode: 33701),
        Charity(id: 55, charityName: "Minnesota Adult & Teen Challenge", profilePhoto: #imageLiteral(resourceName: "Minnesota Adult & Teen Challenge Logo"), backgroundPhoto: #imageLiteral(resourceName: "Minnesota Adult & Teen Challenge Banner"), cause: 3, subCategory: 3, isVerified: true, address: "740 E. 24th St, Minneapolis, MN", zipCode: 55404),
        
        // Health - Medical Research (3.4)
        Charity(id: 56, charityName: "National Pediatric Cancer Foundation", profilePhoto: #imageLiteral(resourceName: "National Pediatric Cancer Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "National Pediatric Cancer Foundation Banner"), cause: 3, subCategory: 4, isVerified: true, address: "5550 Executive Dr, Tampa, FL", zipCode: 33609),
        Charity(id: 57, charityName: "Cure Alzheimer's Fund", profilePhoto: #imageLiteral(resourceName: "Cure Alzheimer's Fund Logo"), backgroundPhoto: #imageLiteral(resourceName: "Cure Alzheimer's Fund Banner"), cause: 3, subCategory: 4, isVerified: true, address: "34 Washington St, Wellesley Hills, MA", zipCode: 02481),
        Charity(id: 58, charityName: "The Lustgarten Foundation for Pancreatic Cancer Research", profilePhoto: #imageLiteral(resourceName: "The Lustgarten Foundation for Pancreatic Cancer Research Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Lustgarten Foundation for Pancreatic Cancer Research Banner"), cause: 3, subCategory: 4, isVerified: true, address: "415 Crossways Park Drive, Woodbury, NY", zipCode: 11797),
        Charity(id: 59, charityName: "Arthritis National Research Foundation", profilePhoto: #imageLiteral(resourceName: "Arthritis National Research Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Arthritis National Research Foundation Banner"), cause: 3, subCategory: 4, isVerified: true, address: "1355 Peachtree St NE, Atlanta, GA", zipCode: 30309),
        Charity(id: 60, charityName: "Alex's Lemonade Stand Foundation", profilePhoto: #imageLiteral(resourceName: "Alex's Lemonade Stand Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Alex's Lemonade Stand Foundation Banner"), cause: 3, subCategory: 4, isVerified: true, address: "111 Presidential Blvd, Bala Cynwyd, PA", zipCode: 19004),
        
        // Community Development - United Ways (4.1)
        Charity(id: 61, charityName: "United Way of Central Indiana", profilePhoto: #imageLiteral(resourceName: "United Way of Central Indiana Logo"), backgroundPhoto: #imageLiteral(resourceName: "United Way of Central Indiana Banner"), cause: 4, subCategory: 1, isVerified: true, address: "2955 N. Meridian Street, Indianapolis, IN", zipCode: 46208),
        Charity(id: 62, charityName: "United Way of Blount County", profilePhoto: #imageLiteral(resourceName: "United Way of Blount County Logo"), backgroundPhoto: #imageLiteral(resourceName: "United Way of Blount County Banner"), cause: 4, subCategory: 1, isVerified: true, address: "1615 E Broadway Ave, Maryville, TN", zipCode: 37804),
        Charity(id: 63, charityName: "United Way of Bartholomew County", profilePhoto: #imageLiteral(resourceName: "United Way of Blount County Logo"), backgroundPhoto: #imageLiteral(resourceName: "United Way of Bartholomew County Banner"), cause: 4, subCategory: 1, isVerified: true, address: "1531 13th St, Columbus, IN", zipCode: 47201),
        Charity(id: 64, charityName: "United Way of Central Alabama", profilePhoto: #imageLiteral(resourceName: "United Way of Blount County Logo"), backgroundPhoto: #imageLiteral(resourceName: "United Way of Central Alabama Banner"), cause: 4, subCategory: 1, isVerified: true, address: "3600 8th Ave S, Birmingham, AL", zipCode: 35222),
        Charity(id: 65, charityName: "United Way of Southern Chautauqua County", profilePhoto: #imageLiteral(resourceName: "United Way of Blount County Logo"), backgroundPhoto: #imageLiteral(resourceName: "United Way of Southern Chautauqua County Banner"), cause: 4, subCategory: 1, isVerified: true, address: "208 Pine St, Jamestown, NY", zipCode: 14701),
        
        // Community Development - Jewish Federations (4.2)
        Charity(id: 66, charityName: "Iranian American Jewish Federation of New York", profilePhoto: #imageLiteral(resourceName: "Iranian American Jewish Federation of New York Logo"), backgroundPhoto: #imageLiteral(resourceName: "Iranian American Jewish Federation of New York Banner"), cause: 4, subCategory: 2, isVerified: true, address: "", zipCode: 0),
        Charity(id: 67, charityName: "Jewish Federation of Delaware", profilePhoto: #imageLiteral(resourceName: "Jewish Federation of Delaware Logo"), backgroundPhoto: #imageLiteral(resourceName: "Jewish Federation of Delaware Banner"), cause: 4, subCategory: 2, isVerified: true, address: "101 Garden of Eden Rd, Wilmington, DE ", zipCode: 19803),
        Charity(id: 68, charityName: "The Associated Jewish Community Federation of Baltimore", profilePhoto: #imageLiteral(resourceName: "Jewish Federation of Delaware Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Associated- Jewish Community Federation of Baltimore Banner"), cause: 4, subCategory: 2, isVerified: true, address: "101 W Mt Royal Ave, Baltimore, MD", zipCode: 21201),
        Charity(id: 69, charityName: "Jewish Federation of Greater Ann Arbor", profilePhoto: #imageLiteral(resourceName: "Jewish Federation of Delaware Logo"), backgroundPhoto: #imageLiteral(resourceName: "Jewish Federation of Greater Ann Arbor Banner"), cause: 4, subCategory: 2, isVerified: true, address: "2939 Birch Hollow Dr, Ann Arbor, MI", zipCode: 48108),
        Charity(id: 70, charityName: "Jewish Federation of Silicon Valley", profilePhoto: #imageLiteral(resourceName: "Jewish Federation of Delaware Logo"), backgroundPhoto: #imageLiteral(resourceName: "Jewish Federation of Silicon Valley Banner"), cause: 4, subCategory: 2, isVerified: true, address: "14855 Oka Rd # 200, Los Gatos, CA", zipCode: 95032),
        
        // Community Development - Community Foundations (4.3)
        Charity(id: 71, charityName: "Parasol Tahoe Community Foundation", profilePhoto: #imageLiteral(resourceName: "Parasol Tahoe Community Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Parasol Tahoe Community Foundation Banner"), cause: 4, subCategory: 3, isVerified: true, address: "948 Incline Way, Incline Village, NV", zipCode: 89451),
        Charity(id: 72, charityName: "The Winston-Salem Foundation", profilePhoto: #imageLiteral(resourceName: "The Winston-Salem Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Winston-Salem Foundation Banner"), cause: 4, subCategory: 3, isVerified: true, address: "751 W 4th St Suite 200, Winston-Salem, NC", zipCode: 27101),
        Charity(id: 73, charityName: "Community Foundation of New Jersey", profilePhoto: #imageLiteral(resourceName: "Community Foundation of New Jersey Logo"), backgroundPhoto: #imageLiteral(resourceName: "Community Foundation of New Jersey Banner"), cause: 4, subCategory: 3, isVerified: true, address: "35 Knox Hill Rd, Morristown, NJ", zipCode: 07960),
        Charity(id: 74, charityName: "North Texas Community Foundation", profilePhoto: #imageLiteral(resourceName: "North Texas Community Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "North Texas Community Foundation Banner"), cause: 4, subCategory: 3, isVerified: true, address: "306 W 7th St #1045, Fort Worth, TX", zipCode: 76102),
        Charity(id: 75, charityName: "Central Indiana Community Foundation", profilePhoto: #imageLiteral(resourceName: "Central Indiana Community Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Central Indiana Community Foundation Banner"), cause: 4, subCategory: 3, isVerified: true, address: "615 N Alabama St, Indianapolis, IN", zipCode: 46204),
        
        // Community Development - Housing & Neighborhood Developments (4.4)
        Charity(id: 76, charityName: "Habitat for Humanity of Collier County", profilePhoto: #imageLiteral(resourceName: "Habitat for Humanity of Collier County Logo"), backgroundPhoto: #imageLiteral(resourceName: "Habitat for Humanity of Collier County Banner"), cause: 4, subCategory: 4, isVerified: true, address: "11145 Tamiami Trail East Naples, FL", zipCode: 34113),
        Charity(id: 77, charityName: "Habitat for Humanity of San Antonio", profilePhoto: #imageLiteral(resourceName: "Habitat for Humanity of San Antonio Logo"), backgroundPhoto: #imageLiteral(resourceName: "Habitat for Humanity of San Antonio Banner"), cause: 4, subCategory: 4, isVerified: true, address: "311 Probandt, San Antonio, TX", zipCode: 78204),
        Charity(id: 78, charityName: "Habitat for Humanity of Ventura County", profilePhoto: #imageLiteral(resourceName: "Habitat for Humanity of Ventura County Logo"), backgroundPhoto: #imageLiteral(resourceName: "Habitat for Humanity of Ventura County Banner"), cause: 4, subCategory: 4, isVerified: true, address: "1850 Eastman Ave, Oxnard, CA", zipCode: 93030),
        Charity(id: 79, charityName: "San Gabriel Valley Habitat for Humanity", profilePhoto: #imageLiteral(resourceName: "San Gabriel Valley Habitat for Humanity Logo"), backgroundPhoto: #imageLiteral(resourceName: "San Gabriel Valley Habitat for Humanity Banner"), cause: 4, subCategory: 4, isVerified: true, address: "400 S Irwindale Ave, Azusa, CA ", zipCode: 91702),
        Charity(id: 80, charityName: "Enterprise Community Partners", profilePhoto: #imageLiteral(resourceName: "Enterprise Community Partners Logo"), backgroundPhoto: #imageLiteral(resourceName: "Enterprise Community Partners Banner"), cause: 4, subCategory: 4, isVerified: true, address: "110 16th Street, Denver, CO", zipCode: 80202),
        
        // Human Services - Children's & Family Services (5.1)
        Charity(id: 81, charityName: "Hour Children", profilePhoto: #imageLiteral(resourceName: "Hour Children Logo"), backgroundPhoto: #imageLiteral(resourceName: "Hour Children Banner"), cause: 5, subCategory: 1, isVerified: true, address: "12th St, Long Island City, NY", zipCode: 11106),
        Charity(id: 82, charityName: "Jewish Family Service of Metrowest", profilePhoto: #imageLiteral(resourceName: "Jewish Family Service of Metrowest Logo"), backgroundPhoto: #imageLiteral(resourceName: "Jewish Family Service of Metrowest Banner"), cause: 5, subCategory: 1, isVerified: true, address: "475 Franklin St, Framingham, MA", zipCode: 01702),
        Charity(id: 83, charityName: "Lifesong for Orphans", profilePhoto: #imageLiteral(resourceName: "Lifesong for Orphans Logo"), backgroundPhoto: #imageLiteral(resourceName: "Lifesong for Orphans Banner"), cause: 5, subCategory: 1, isVerified: true, address: "", zipCode: 0),
        Charity(id: 84, charityName: "Families Forward", profilePhoto: #imageLiteral(resourceName: "Families Forward Logo"), backgroundPhoto: #imageLiteral(resourceName: "Families Forward Banner"), cause: 5, subCategory: 1, isVerified: true, address: "8 Thomas, Irvine, CA ", zipCode: 92618),
        Charity(id: 85, charityName: "Caridad Center", profilePhoto: #imageLiteral(resourceName: "Caridad Center Logo"), backgroundPhoto: #imageLiteral(resourceName: "Caridad Center Banner"), cause: 5, subCategory: 1, isVerified: true, address: "8645 W Boynton Beach Blvd, Boynton Beach, FL", zipCode: 33472),
        
        // Human Services - Youth Development, Shelter, & Crisis Services (5.2)
        Charity(id: 86, charityName: "Boys & Girls Clubs of Nassau County Foundation", profilePhoto: #imageLiteral(resourceName: "Boys & Girls Clubs of Nassau County Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Boys & Girls Clubs of Nassau County Foundation Banner"), cause: 5, subCategory: 2, isVerified: true, address: "942259 Old Nassauville Rd, Fernandina Beach, FL", zipCode: 32034),
        Charity(id: 87, charityName: "Fresh Youth Initiatives", profilePhoto: #imageLiteral(resourceName: "Fresh Youth Initiatives Logo"), backgroundPhoto: #imageLiteral(resourceName: "Fresh Youth Initiatives Banner"), cause: 5, subCategory: 2, isVerified: true, address: "505 W 171st St, New York, NY", zipCode: 10032),
        Charity(id: 88, charityName: "Place of Hope", profilePhoto: #imageLiteral(resourceName: "Place of Hope Logo"), backgroundPhoto: #imageLiteral(resourceName: "Place of Hope Banner"), cause: 5, subCategory: 2, isVerified: true, address: "9078 Isaiah Lane, Palm Beach Gardens, FL", zipCode: 33418),
        Charity(id: 89, charityName: "Boy Scouts of America, Long Beach Area Council", profilePhoto: #imageLiteral(resourceName: "Boy Scouts of America, Long Beach Area Council Logo"), backgroundPhoto: #imageLiteral(resourceName: "Boy Scouts of America, Long Beach Area Council Banner"), cause: 5, subCategory: 2, isVerified: true, address: "401 E 37th St, Long Beach, CA", zipCode: 90807),
        Charity(id: 90, charityName: "Covenant House New Orleans", profilePhoto: #imageLiteral(resourceName: "Covenant House New Orleans Logo"), backgroundPhoto: #imageLiteral(resourceName: "Covenant House New Orleans Banner"), cause: 5, subCategory: 2, isVerified: true, address: "611 N Rampart St, New Orleans, LA", zipCode: 70112),
        
        // Human Services - Food Banks, Food Pantires, & Food Distribution (5.3)
        Charity(id: 91, charityName: "Food Bank of Siouxland", profilePhoto: #imageLiteral(resourceName: "Food Bank of Siouxland Logo"), backgroundPhoto: #imageLiteral(resourceName: "Food Bank of Siouxland Banner"), cause: 5, subCategory: 3, isVerified: true, address: "1313 11th St, Sioux City, IA", zipCode: 51105),
        Charity(id: 92, charityName: "The Foodbank", profilePhoto: #imageLiteral(resourceName: "Food Bank of Siouxland Banner"), backgroundPhoto: #imageLiteral(resourceName: "Food Bank of Siouxland Logo"), cause: 5, subCategory: 3, isVerified: true, address: "", zipCode: 0),
        Charity(id: 93, charityName: "North Helpline", profilePhoto: #imageLiteral(resourceName: "North Helpline Logo"), backgroundPhoto: #imageLiteral(resourceName: "North Helpline Banner"), cause: 5, subCategory: 3, isVerified: true, address: "12736 33rd Ave NE, Seattle, WA", zipCode: 98125),
        Charity(id: 94, charityName: "Second Harvest Foodbank of the Mahoning Valley", profilePhoto: #imageLiteral(resourceName: "Second Harvest Foodbank of the Mahoning Valley Logo"), backgroundPhoto: #imageLiteral(resourceName: "Second Harvest Foodbank of the Mahoning Valley Banner"), cause: 5, subCategory: 3, isVerified: true, address: "2805 Salt Springs Rd, Youngstown, OH", zipCode: 44509),
        Charity(id: 95, charityName: "Weld Food Bank", profilePhoto: #imageLiteral(resourceName: "Weld Food Bank Logo"), backgroundPhoto: #imageLiteral(resourceName: "Weld Food Bank Banner"), cause: 5, subCategory: 3, isVerified: true, address: "1108 H St, Greeley, CO", zipCode: 80631),
        
        // Human Services - Multipurpose Human Service Organizations (5.4)
        Charity(id: 96, charityName: "YWCA Richmond", profilePhoto: #imageLiteral(resourceName: "YWCA Richmond Logo"), backgroundPhoto: #imageLiteral(resourceName: "YWCA Richmond Banner"), cause: 5, subCategory: 4, isVerified: true, address: "6 N 5th St, Richmond, VA", zipCode: 23219),
        Charity(id: 97, charityName: "All Hands and Hearts Smart Response", profilePhoto: #imageLiteral(resourceName: "All Hands and Hearts Smart Response Logo"), backgroundPhoto: #imageLiteral(resourceName: "All Hands and Hearts Smart Response Banner"), cause: 5, subCategory: 4, isVerified: true, address: "6 County Road, Mattapoisett, MA", zipCode: 02739),
        Charity(id: 98, charityName: "FDNY Foundation", profilePhoto: #imageLiteral(resourceName: "FDNY Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "FDNY Foundation Banner"), cause: 5, subCategory: 4, isVerified: true, address: "9 MetroTech Center, Brooklyn, NY", zipCode: 11201),
        Charity(id: 99, charityName: "PeacePlayers International", profilePhoto: #imageLiteral(resourceName: "PeacePlayers International Logo"), backgroundPhoto: #imageLiteral(resourceName: "PeacePlayers International Banner"), cause: 5, subCategory: 4, isVerified: true, address: "1200 New Hampshire Ave, Washington, D.C.", zipCode: 20036),
        Charity(id: 100, charityName: "Concerns of Police Survivors", profilePhoto: #imageLiteral(resourceName: "Concerns of Police Survivors Logo"), backgroundPhoto: #imageLiteral(resourceName: "Concerns of Police Survivors Banner"), cause: 5, subCategory: 4, isVerified: true, address: "846 Old South 5, Camdenton, MO", zipCode: 65020),
        
        // Human Services - Homeless Services (5.5)
        Charity(id: 101, charityName: "A Magic City Christmas", profilePhoto: #imageLiteral(resourceName: "A Magic City Christmas Logo"), backgroundPhoto: #imageLiteral(resourceName: "A Magic City Christmas Banner"), cause: 5, subCategory: 5, isVerified: true, address: "", zipCode: 0),
        Charity(id: 102, charityName: "Abode Services", profilePhoto: #imageLiteral(resourceName: "Abode Services Logo"), backgroundPhoto: #imageLiteral(resourceName: "Abode Services Banner"), cause: 5, subCategory: 5, isVerified: true, address: "40849 Fremont Blvd, Fremont, CA", zipCode: 94538),
        Charity(id: 103, charityName: "ACCESS", profilePhoto: #imageLiteral(resourceName: "ACCESS Logo"), backgroundPhoto: #imageLiteral(resourceName: "ACCESS Banner"), cause: 5, subCategory: 5, isVerified: true, address: "", zipCode: 0),
        Charity(id: 104, charityName: "The Action Center", profilePhoto: #imageLiteral(resourceName: "The Action Center Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Action Center Banner"), cause: 5, subCategory: 5, isVerified: true, address: "8755 W 14th Ave, Lakewood, CO", zipCode: 80215),
        Charity(id: 105, charityName: "Adopt-A-Family", profilePhoto: #imageLiteral(resourceName: "Adopt-A-Family Logo"), backgroundPhoto: #imageLiteral(resourceName: "Adopt-A-Family Banner"), cause: 5, subCategory: 5, isVerified: true, address: "6100 Smith Road Denver, CO", zipCode: 80216),
        
        // Human Services - Social Services (5.6)
        Charity(id: 106, charityName: "Challenge Aspen", profilePhoto: #imageLiteral(resourceName: "Challenge Aspen Logo"), backgroundPhoto: #imageLiteral(resourceName: "Challenge Aspen Banner"), cause: 5, subCategory: 6, isVerified: true, address: "Snowmass Village Mall, Snowmass Village, CO", zipCode: 81615),
        Charity(id: 107, charityName: "Fisher House Foundation", profilePhoto: #imageLiteral(resourceName: "Fisher House Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Fisher House Foundation Banner"), cause: 5, subCategory: 6, isVerified: true, address: "12300 Twinbrook Pkwy, Rockville, MD", zipCode: 20852),
        Charity(id: 108, charityName: "Kostopulos Dream Foundation", profilePhoto: #imageLiteral(resourceName: "Kostopulos Dream Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Kostopulos Dream Foundation Banner"), cause: 5, subCategory: 6, isVerified: true, address: "4180 Emigration Canyon Rd, Salt Lake City, UT", zipCode: 84108),
        Charity(id: 109, charityName: "Navy SEAL Foundation", profilePhoto: #imageLiteral(resourceName: "Navy SEAL Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "Navy SEAL Foundation Banner"), cause: 5, subCategory: 6, isVerified: true, address: "1619 D Stree, Virginia Beach, VA", zipCode: 23459),
        Charity(id: 110, charityName: "The Women's Center of Tarrant County", profilePhoto: #imageLiteral(resourceName: "The Women's Center of Tarrant County Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Women's Center of Tarrant County Banner"), cause: 5, subCategory: 6, isVerified: true, address: "1723 Hemphill, Fort Worth, TX", zipCode: 76110),
        
        // International - Development & Releif Services (6.1)
        Charity(id: 111, charityName: "Asha for Education", profilePhoto: #imageLiteral(resourceName: "Asha for Education Logo"), backgroundPhoto: #imageLiteral(resourceName: "Asha for Education Banner"), cause: 6, subCategory: 1, isVerified: true, address: "340 S LEMON AVE, WALNUT, CA", zipCode: 91789),
        Charity(id: 112, charityName: "Association for India's Development", profilePhoto: #imageLiteral(resourceName: "Association for India's Development Logo"), backgroundPhoto: #imageLiteral(resourceName: "Association for India's Development Banner"), cause: 6, subCategory: 1, isVerified: true, address: "5011 Tecumseh Street, College Park, MD", zipCode: 20740),
        Charity(id: 113, charityName: "Global Greengrants Fund", profilePhoto: #imageLiteral(resourceName: "Global Greengrants Fund Logo"), backgroundPhoto: #imageLiteral(resourceName: "Global Greengrants Fund Banner"), cause: 6, subCategory: 1, isVerified: true, address: "2840 Wilderness Pl, Boulder, CO", zipCode: 80301),
        Charity(id: 114, charityName: "Hope for Haiti's Children", profilePhoto: #imageLiteral(resourceName: "Hope for Haiti's Children Logo"), backgroundPhoto: #imageLiteral(resourceName: "Hope for Haiti's Children Banner"), cause: 6, subCategory: 1, isVerified: true, address: "12020 Southwick Ln, Cincinnati, OH", zipCode: 45011),
        Charity(id: 115, charityName: "India Development and Relief Fund, Inc. (IDRF)", profilePhoto: #imageLiteral(resourceName: "India Development and Relief Fund, Inc. (IDRF) Logo"), backgroundPhoto: #imageLiteral(resourceName: "India Development and Relief Fund, Inc. (IDRF) Banner"), cause: 6, subCategory: 1, isVerified: true, address: "5821 Mossrock Drive, North Bethesda, MD", zipCode: 20852),
        
        // International - Internation Peace, Security, & Affairs (6.2)
        Charity(id: 116, charityName: "White Ribbon Alliance", profilePhoto: #imageLiteral(resourceName: "White Ribbon Alliance Logo"), backgroundPhoto: #imageLiteral(resourceName: "White Ribbon Alliance Banner"), cause: 6, subCategory: 2, isVerified: true, address: "", zipCode: 0),
        Charity(id: 117, charityName: "The Prem Rawat Foundation", profilePhoto: #imageLiteral(resourceName: "The Prem Rawat Foundation Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Prem Rawat Foundation Banner"), cause: 6, subCategory: 2, isVerified: true, address: "", zipCode: 0),
        Charity(id: 118, charityName: "EarthRights International", profilePhoto: #imageLiteral(resourceName: "EarthRights International Logo"), backgroundPhoto: #imageLiteral(resourceName: "EarthRights International Banner"), cause: 6, subCategory: 2, isVerified: true, address: "1612 K St NW, Washington, DC", zipCode: 20006),
        Charity(id: 119, charityName: "Just Detention International", profilePhoto: #imageLiteral(resourceName: "Just Detention International Logo"), backgroundPhoto: #imageLiteral(resourceName: "Just Detention International Banner"), cause: 6, subCategory: 2, isVerified: true, address: "3325 Wilshire Blvd, Los Angeles, CA", zipCode: 90010),
        Charity(id: 120, charityName: "The Carter Center", profilePhoto: #imageLiteral(resourceName: "The Carter Center Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Carter Center Banner"), cause: 6, subCategory: 2, isVerified: true, address: "453 John Lewis Freedom Pkwy NE, Atlanta, GA", zipCode: 30307),
        
        // International - Humanitarian Releif Support (6.3)
        Charity(id: 121, charityName: "MAP International", profilePhoto: #imageLiteral(resourceName: "MAP International Logo"), backgroundPhoto: #imageLiteral(resourceName: "MAP International Banner"), cause: 6, subCategory: 3, isVerified: true, address: "315 W. Ponce de Leon Ave, Decatur, GA", zipCode: 30030),
        Charity(id: 122, charityName: "Books For Africa", profilePhoto: #imageLiteral(resourceName: "Books For Africa Logo"), backgroundPhoto: #imageLiteral(resourceName: "Books For Africa Banner"), cause: 6, subCategory: 3, isVerified: true, address: "370 Selby Ave, Saint Paul, MN", zipCode: 55102),
        Charity(id: 123, charityName: "Direct Relief", profilePhoto: #imageLiteral(resourceName: "Direct Relief Logo"), backgroundPhoto: #imageLiteral(resourceName: "Direct Relief Banner"), cause: 6, subCategory: 3, isVerified: true, address: "6100 Wallace Becknell Rd, Santa Barbara, California", zipCode: 93117),
        Charity(id: 124, charityName: "Matthew 25 Ministries", profilePhoto: #imageLiteral(resourceName: "Matthew 25- Ministries Logo"), backgroundPhoto: #imageLiteral(resourceName: "Matthew 25- Ministries Banner"), cause: 6, subCategory: 3, isVerified: true, address: "11060 Kenwood Road, Cincinnati, Ohio", zipCode: 45242),
        Charity(id: 125, charityName: "Vitamin Angels", profilePhoto: #imageLiteral(resourceName: "Vitamin Angels Logo"), backgroundPhoto: #imageLiteral(resourceName: "Vitamin Angels Banner"), cause: 6, subCategory: 3, isVerified: true, address: "111 W. Micheltorena, Santa Barbara, CA", zipCode: 93101),
        
        // Animals - Animal Rights, Welfare, & Services (7.1)
        Charity(id: 126, charityName: "Greenville Humane Society", profilePhoto: #imageLiteral(resourceName: "Greenville Humane Society Logo"), backgroundPhoto: #imageLiteral(resourceName: "Greenville Humane Society Banner"), cause: 7, subCategory: 1, isVerified: true, address: "305 Airport Rd, Greenville, SC", zipCode: 29607),
        Charity(id: 127, charityName: "Israel Guide Dog Center for the Blind", profilePhoto: #imageLiteral(resourceName: "Israel Guide Dog Center for the Blind Logo"), backgroundPhoto: #imageLiteral(resourceName: "Israel Guide Dog Center for the Blind Banner"), cause: 7, subCategory: 1, isVerified: true, address: "Derech HaSadot 6, Beit Oved, 7680000, Israel", zipCode: 0),
        Charity(id: 128, charityName: "Nevada Humane Society", profilePhoto: #imageLiteral(resourceName: "Nevada Humane Society Logo"), backgroundPhoto: #imageLiteral(resourceName: "Nevada Humane Society Banner"), cause: 7, subCategory: 1, isVerified: true, address: "2825 Longley Lane, Reno, NV", zipCode: 89502),
        Charity(id: 129, charityName: "PAWS Chicago", profilePhoto: #imageLiteral(resourceName: "PAWS Chicago Logo"), backgroundPhoto: #imageLiteral(resourceName: "PAWS Chicago Banner"), cause: 7, subCategory: 1, isVerified: true, address: "1997 N Clybourn Ave, Chicago, IL", zipCode: 60614),
        Charity(id: 130, charityName: "Tri County Humane Society", profilePhoto: #imageLiteral(resourceName: "Tri County Humane Society Logo"), backgroundPhoto: #imageLiteral(resourceName: "Tri County Humane Society Banner"), cause: 7, subCategory: 1, isVerified: true, address: "735 8th St NE, St Cloud, MN", zipCode: 56304),
        
        // Animals - Wildlife Conservation (7.2)
        Charity(id: 131, charityName: "Big Cat Rescue", profilePhoto: #imageLiteral(resourceName: "Big Cat Rescue Logo"), backgroundPhoto: #imageLiteral(resourceName: "Big Cat Rescue Banner"), cause: 7, subCategory: 2, isVerified: true, address: "12802 Easy St, Tampa, FL", zipCode: 33625),
        Charity(id: 132, charityName: "WildAid", profilePhoto: #imageLiteral(resourceName: "WildAid Logo"), backgroundPhoto: #imageLiteral(resourceName: "WildAid Banner"), cause: 7, subCategory: 2, isVerified: true, address: "333 Pine Street, San Francisco, CA", zipCode: 94104),
        Charity(id: 133, charityName: "Wildlife Conservation Network", profilePhoto: #imageLiteral(resourceName: "Wildlife Conservation Network Logo"), backgroundPhoto: #imageLiteral(resourceName: "Wildlife Conservation Network Banner"), cause: 7, subCategory: 2, isVerified: true, address: "209 Mississippi Street. San Francisco, CA", zipCode: 94107),
        Charity(id: 134, charityName: "Our Companions Animal Rescue", profilePhoto: #imageLiteral(resourceName: "Our Companions Animal Rescue Logo"), backgroundPhoto: #imageLiteral(resourceName: "Our Companions Animal Rescue Banner"), cause: 7, subCategory: 2, isVerified: true, address: "34 Sanrico Drive, Manchester, CT", zipCode: 06042),
        Charity(id: 135, charityName: "The Elephant Sanctuary", profilePhoto: #imageLiteral(resourceName: "The Elephant Sanctuary Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Elephant Sanctuary Banner"), cause: 7, subCategory: 2, isVerified: true, address: "27 E Main St, Hohenwald, TN", zipCode: 38462),
        
        // Animals - Zoos and Aquariums (7.3)
        Charity(id: 136, charityName: "The Toledo Zoo", profilePhoto: #imageLiteral(resourceName: "The Toledo Zoo Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Toledo Zoo Banner"), cause: 7, subCategory: 3, isVerified: true, address: "2 Hippo Way, Toledo, OH", zipCode: 43609),
        Charity(id: 137, charityName: "Nashville Zoo", profilePhoto: #imageLiteral(resourceName: "Nashville Zoo Logo"), backgroundPhoto: #imageLiteral(resourceName: "Nashville Zoo Banner"), cause: 7, subCategory: 3, isVerified: true, address: "3777 Nolensville Pike, Nashville, TN", zipCode: 37211),
        Charity(id: 138, charityName: "The Living Desert", profilePhoto: #imageLiteral(resourceName: "The Living Desert Logo"), backgroundPhoto: #imageLiteral(resourceName: "The Living Desert Banner"), cause: 7, subCategory: 3, isVerified: true, address: "47900 Portola Ave, Palm Desert, CA", zipCode: 92260),
        Charity(id: 139, charityName: "Monterey Bay Aquarium", profilePhoto: #imageLiteral(resourceName: "Monterey Bay Aquarium Logo"), backgroundPhoto: #imageLiteral(resourceName: "Monterey Bay Aquarium Banner"), cause: 7, subCategory: 3, isVerified: true, address: "886 Cannery Row, Monterey, CA", zipCode: 93940),
        Charity(id: 140, charityName: "North Carolina Zoological Society", profilePhoto: #imageLiteral(resourceName: "North Carolina Zoological Society Logo"), backgroundPhoto: #imageLiteral(resourceName: "North Carolina Zoological Society Banner"), cause: 7, subCategory: 3, isVerified: true, address: "4403 Zoo Pkwy, Asheboro, NC", zipCode: 27205),
        
        //Added later
//        Charity(id: 141, charityName: "Environment Learning for Kids", profilePhoto: UIImage(named: "ELK_profile_pic"), backgroundPhoto: UIImage(named: "ELK_Banner"), cause: 4, subCategory: 3, isVerified: true, address: "6060 Broadway, Denver, CO", zipCode: 80216),
        Charity(id: 142, charityName: "UNICEF", profilePhoto: UIImage(named: "unicef_profile_pic"), backgroundPhoto: UIImage(named: "unicef_banner"), cause: 1, subCategory: 5, isVerified: true, address: "125 Maiden Lane New York, NY", zipCode: 10038),
        Charity(id: 143, charityName: "The Nature Conservancy", profilePhoto: UIImage(named: "the_nature_conservancy_profile_pic"), backgroundPhoto: UIImage(named: "the-nature-conservancy_banner"), cause: 2, subCategory: 5, isVerified: true, address: "4245 North Fairfax Drive, Arlington, Virginia", zipCode: 22203),
        Charity(id: 144, charityName: "St. Judes", profilePhoto: UIImage(named: "saint_judes_profile_pic"), backgroundPhoto: UIImage(named: "saint_judes_banner"), cause: 3, subCategory: 2 , isVerified: true, address: "262 Danny Thomas Place, Memphis, TN", zipCode: 38105),
        Charity(id: 145, charityName: "United Way", profilePhoto: UIImage(named: "united_way_profile_pic"), backgroundPhoto: UIImage(named: "united_way_banner"), cause: 4, subCategory: 1, isVerified: true, address: "701 N. Fairfax Street Alexandria, VA", zipCode: 22314),
        Charity(id: 146, charityName: "Feeding America", profilePhoto: UIImage(named: "feeding_america_profile_pic"), backgroundPhoto: UIImage(named: "feeding-america-banner"), cause: 5, subCategory: 5, isVerified: true, address: "35 East Wacker Drive, Suite 2000 Chicago, IL", zipCode: 60601),
        Charity(id: 147, charityName: "The Red Cross", profilePhoto: UIImage(named: "red_cross_profile_pic"), backgroundPhoto: UIImage(named: "red_cross_banner"), cause: 6, subCategory: 3, isVerified: true, address: "431 18th Street, NW Washington, DC", zipCode: 20006),
        Charity(id: 148, charityName: "World Wildlife Fund", profilePhoto: UIImage(named: "world_wildlife_fund_profile_pic"), backgroundPhoto: UIImage(named: "world_wildlife_fund_banner"), cause: 7, subCategory: 2, isVerified: true, address: "1250 24th Street, N.W. Washington, DC", zipCode: 20037),
    ]
    
    static var allBusinesses = [
        Business(id: 1, name: "Facebook", primaryEmail: "facebook@gmail.com", profilePhoto: #imageLiteral(resourceName: "facebookIcon"), backgroundPhoto: #imageLiteral(resourceName: "11"), isVerified: true),
        Business(id: 2, name: "Google", primaryEmail: "google@gmail.com", profilePhoto: #imageLiteral(resourceName: "googleIcon"), backgroundPhoto: #imageLiteral(resourceName: "10"), isVerified: true),
        Business(id: 3, name: "Amazon", primaryEmail: "amazon@gmail.com", profilePhoto: #imageLiteral(resourceName: "amazonIcon"), backgroundPhoto: #imageLiteral(resourceName: "14"), isVerified: true),
    ]
    
    static var allUsers = [
        User(id: 1, firstName: "Justin", lastName: "Frazer", username: "jfrazer", phoneNumber: "720-939-6936",email: "jfrazer@gmail.com", password: "", birthday: "10-06-1992", primaryCause: 0, profilePhoto: UIImage(named: "justinfrazer")),
        User(id: 2, firstName: "Kevin", lastName: "Frazer", username: "kevfrazer", phoneNumber: "720-666-1142",email: "kevinfrazer@gmail.com", password: "", birthday: "03-03-1960", primaryCause: 0, profilePhoto: UIImage(named: "kevinfrazer")),
        User(id: 3, firstName: "Kim", lastName: "Frazer", username: "kfrazer", phoneNumber: "720-939-6936",email: "kimfrazer@gmail.com", password: "", birthday: "12-23-1959", primaryCause: 0, profilePhoto: UIImage(named: "kimfrazer")),
        User(id: 4, firstName: "Cassie", lastName: "Frazer", username: "cfrazer", phoneNumber: "720-939-0936",email: "cfrazer@gmail.com", password: "", birthday: "09-27-1994", primaryCause: 0, profilePhoto: UIImage(named: "cassiefrazer"))
//        User(id: 5, firstName: "Ellen", lastName: "Degeneres", phoneNumber: "720-939-0936",email: "edegeneres", password: "", birthday: "01-26-1958", primaryCause: 0, profilePhoto: UIImage(named: "ellendegeneres")),
//        User(id: 6, firstName: "Will", lastName: "Smith", phoneNumber: "720-939-0936",email: "wsmith", password: "", birthday: "09-27-1994", primaryCause: 0, profilePhoto: UIImage(named: "willsmith")),
//        User(id: 7, firstName: "Michael", lastName: "Bloomberg", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "michaelbloomberg")),
//        User(id: 8, firstName: "John", lastName: "Legend", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "johnlegend")),
//        User(id: 9, firstName: "Cate", lastName: "Blanchett", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "cateblanchett")),
//        User(id: 10, firstName: "Paul", lastName: "Marciano", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "paulmarciano")),
//        User(id: 11, firstName: "Connie", lastName: "Nielsen", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "connienielsen")),
//        User(id: 12, firstName: "Sanford", lastName: "Weill", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "sanfordweill")),
//        User(id: 13, firstName: "Courtenay", lastName: "Venton", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 5, profilePhoto: UIImage(named: "courtenayventon")),
//        User(id: 14, firstName: "Howard", lastName: "Rachofsky", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "howardrachofsky")),
//        User(id: 15, firstName: "Anna", lastName: "Smith", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 5, profilePhoto: UIImage(named: "annasmith")),
//        User(id: 16, firstName: "Mark", lastName: "Zuckerberg", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "markzuckerberg")),
//        User(id: 17, firstName: "Eli", lastName: "Broad", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "elibroad")),
//        User(id: 18, firstName: "Nicole", lastName: "Hockley", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "nicolehockley")),
//        User(id: 19, firstName: "Todd", lastName: "Wagner", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "toddwagner")),
//        User(id: 20, firstName: "Dustin", lastName: "Moskovitz", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 0, profilePhoto: UIImage(named: "dustinmoskovitz")),
//        User(id: 21, firstName: "Jeff", lastName: "Skoll", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "jeffskoll")),
//        User(id: 22, firstName: "Paul", lastName: "Allen", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "paulallen")),
//        User(id: 23, firstName: "Jon", lastName: "Huntsman", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "jonhuntsman")),
//        User(id: 25, firstName: "John", lastName: "Arnold", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 5, profilePhoto: UIImage(named: "johnarnold")),
//        User(id: 26, firstName: "Nitzia", lastName: "Logothetis", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "nitzialogothetis")),
//        User(id: 27, firstName: "Gbenga", lastName: "Oyebode", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "gbengaoyebode")),
//        User(id: 28, firstName: "Richard", lastName: "Branson", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 4, profilePhoto: UIImage(named: "richardbranson")),
//        User(id: 29, firstName: "Joe", lastName: "Biden", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "joebiden")),
//        User(id: 30, firstName: "Dayle", lastName: "Haddon", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "daylehaddon")),
//        User(id: 31, firstName: "David", lastName: "Miliband", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "davidmiliband")),
//        User(id: 32, firstName: "Luma", lastName: "Mufleh", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "lumamufleh")),
//        User(id: 33, firstName: "Mandy", lastName: "Patinkin", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "mandypatinkin")),
//        User(id: 34, firstName: "Sandra", lastName: "Uwiringiyimana", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "sandrauwiringiyimana")),
//        User(id: 35, firstName: "Lee", lastName: "Min-bok", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 0, profilePhoto: UIImage(named: "leeminbok")),
//        User(id: 36, firstName: "Henry", lastName: "Timms", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 0, profilePhoto: UIImage(named: "henrytimms")),
//        User(id: 37, firstName: "Craig", lastName: "Kielburger", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "craigkielburger")),
//        User(id: 38, firstName: "Mike", lastName: "Porath", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "mikeporath")),
//        User(id: 39, firstName: "Jordan", lastName: "Hewson", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 0, profilePhoto: UIImage(named: "jordanhewson")),
//        User(id: 40, firstName: "Sheryl", lastName: "Sandberg", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 5, profilePhoto: UIImage(named: "sherylsandberg")),
//        User(id: 41, firstName: "Robert", lastName: "Smith", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "robertsmith")),
//        User(id: 42, firstName: "Bill", lastName: "Gates", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "billgates")),
//        User(id: 43, firstName: "Darren", lastName: "Walker", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "darrenwalker")),
//        User(id: 44, firstName: "Chuck", lastName: "Feeney", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "chuckfeeney")),
//        User(id: 45, firstName: "Ron", lastName: "Perelman", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 7, profilePhoto: UIImage(named: "ronperelman")),
//        User(id: 46, firstName: "Pierre", lastName: "Omidyar", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 7, profilePhoto: UIImage(named: "pierreomidyar")),
//        User(id: 47, firstName: "Lilianne", lastName: "Plouman", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 7, profilePhoto: UIImage(named: "lilianneplouman")),
//        User(id: 48, firstName: "Howard", lastName: "Schultz", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 7, profilePhoto: UIImage(named: "howardschultz")),
//        User(id: 49, firstName: "Elaine", lastName: "Wynn", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "elainewynn")),
//        User(id: 50, firstName: "Sean", lastName: "Parker", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 3, profilePhoto: UIImage(named: "seanparker")),
//        User(id: 51, firstName: "Glenn", lastName: "Martin", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 5, profilePhoto: UIImage(named: "glennmartin")),
//        User(id: 52, firstName: "Jacqueline", lastName: "Novogratz", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "jacquelinenovogratz")),
//        User(id: 53, firstName: "Reed", lastName: "Hastings", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "reedhastings")),
//        User(id: 54, firstName: "Charlotte", lastName: "Anderson", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 1, profilePhoto: UIImage(named: "charlotteanderson")),
//        User(id: 55, firstName: "James", lastName: "Simons", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 2, profilePhoto: UIImage(named: "jamessimons")),
//        User(id: 56, firstName: "Roxanne", lastName: "Quimby", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 7, profilePhoto: UIImage(named: "roxannequimby")),
//        User(id: 57, firstName: "Billy", lastName: "Frist", phoneNumber: "",email: "", password: "", birthday: "", primaryCause: 6, profilePhoto: UIImage(named: "billyfrist"))
    ]
    
    static var loggedInUser = allUsers[0]
    
    static var allPosts = [
        Post(id: 1, postOwnerID: 1, postType: 2, postContent: "Post 1", postImage: #imageLiteral(resourceName: "9")),
        Post(id: 2, postOwnerID: 1, postType: 2, postContent: "Post 2", postImage: #imageLiteral(resourceName: "8")),
        Post(id: 3, postOwnerID: 1, postType: 2, postContent: "Post 3", postImage: #imageLiteral(resourceName: "6")),
        Post(id: 4, postOwnerID: 1, postType: 2, postContent: "Post 4", postImage: #imageLiteral(resourceName: "7")),
        Post(id: 5, postOwnerID: 1, postType: 2, postContent: "Post 5", postImage: #imageLiteral(resourceName: "2")),
        Post(id: 6, postOwnerID: 1, postType: 2, postContent: "Post 6", postImage: #imageLiteral(resourceName: "1")),
        Post(id: 7, postOwnerID: 1, postType: 2, postContent: "Post 7", postImage: #imageLiteral(resourceName: "4")),
        Post(id: 8, postOwnerID: 1, postType: 2, postContent: "Post 8", postImage: #imageLiteral(resourceName: "3")),
        Post(id: 9, postOwnerID: 1, postType: 2, postContent: "Post 9", postImage: #imageLiteral(resourceName: "10")),
        Post(id: 10, postOwnerID: 1, postType: 2, postContent: "Post 10", postImage: #imageLiteral(resourceName: "5")),
        Post(id: 11, postOwnerID: 1, postType: 2, postContent: "Post 11", postImage: #imageLiteral(resourceName: "17")),
        Post(id: 12, postOwnerID: 1, postType: 2, postContent: "Post 12", postImage: #imageLiteral(resourceName: "12")),
        Post(id: 13, postOwnerID: 1, postType: 2, postContent: "Post 13", postImage: #imageLiteral(resourceName: "20")),
        Post(id: 14, postOwnerID: 1, postType: 2, postContent: "Post 14", postImage: #imageLiteral(resourceName: "11")),
        Post(id: 15, postOwnerID: 1, postType: 2, postContent: "Post 15", postImage: #imageLiteral(resourceName: "19")),
        Post(id: 16, postOwnerID: 1, postType: 2, postContent: "Post 16", postImage: #imageLiteral(resourceName: "13")),
        Post(id: 17, postOwnerID: 1, postType: 2, postContent: "Post 17", postImage: #imageLiteral(resourceName: "16")),
        Post(id: 18, postOwnerID: 1, postType: 2, postContent: "Post 18", postImage: #imageLiteral(resourceName: "14")),
        Post(id: 19, postOwnerID: 1, postType: 2, postContent: "Post 19", postImage: #imageLiteral(resourceName: "18")),
        Post(id: 20, postOwnerID: 1, postType: 2, postContent: "Post 20", postImage: #imageLiteral(resourceName: "15")),
        Post(id: 21, postOwnerID: 1, postType: 2, postContent: "Post 21", postImage: #imageLiteral(resourceName: "23")),
        Post(id: 22, postOwnerID: 1, postType: 2, postContent: "Post 22", postImage: #imageLiteral(resourceName: "22")),
        Post(id: 23, postOwnerID: 1, postType: 2, postContent: "Post 23", postImage: #imageLiteral(resourceName: "27")),
        Post(id: 24, postOwnerID: 1, postType: 2, postContent: "Post 24", postImage: #imageLiteral(resourceName: "28")),
        Post(id: 25, postOwnerID: 1, postType: 2, postContent: "Post 25", postImage: #imageLiteral(resourceName: "25")),
        Post(id: 26, postOwnerID: 1, postType: 2, postContent: "Post 26", postImage: #imageLiteral(resourceName: "26")),
        Post(id: 27, postOwnerID: 1, postType: 2, postContent: "Post 27", postImage: #imageLiteral(resourceName: "29")),
        Post(id: 28, postOwnerID: 1, postType: 2, postContent: "Post 28", postImage: #imageLiteral(resourceName: "24")),
        Post(id: 29, postOwnerID: 1, postType: 2, postContent: "Post 29", postImage: #imageLiteral(resourceName: "21")),
        Post(id: 30, postOwnerID: 1, postType: 2, postContent: "Post 30", postImage: #imageLiteral(resourceName: "30")),
        Post(id: 31, postOwnerID: 1, postType: 1, postContent: "Pokemon 1", postImage: #imageLiteral(resourceName: "pokemon#1Thumbnail")),
        Post(id: 32, postOwnerID: 1, postType: 1, postContent: "Pokemon 2", postImage: #imageLiteral(resourceName: "pokemon#2Thumbnail")),
        Post(id: 33, postOwnerID: 1, postType: 1, postContent: "Giving Gift Cards to Strangers", postImage: #imageLiteral(resourceName: "giftCardsThumbnail")),
        Post(id: 34, postOwnerID: 1, postType: 1, postContent: "Giving Cash to Strangers", postImage: #imageLiteral(resourceName: "givingCashToStrangers")),
        Post(id: 35, postOwnerID: 1, postType: 1, postContent: "Giving to the Homeless", postImage: #imageLiteral(resourceName: "homeless")),
        Post(id: 36, postOwnerID: 1, postType: 1, postContent: "Panhandling with the Homeless", postImage: #imageLiteral(resourceName: "panhandlingThumbnail")),
        Post(id: 37, postOwnerID: 1, postType: 1, postContent: "Giving Gift Cards to Mines Students", postImage: #imageLiteral(resourceName: "minesThumbnail")),
        Post(id: 38, postOwnerID: 1, postType: 1, postContent: "Let's Change the World", postImage: #imageLiteral(resourceName: "changeTheWorldThumbnail")),
        Post(id: 39, postOwnerID: 1, postType: 1, postContent: "Giving to the People of Mexico", postImage: #imageLiteral(resourceName: "mexicoThumbnail")),
        Post(id: 40, postOwnerID: 1, postType: 1, postContent: "My $600 Mother Day Surprise", postImage: #imageLiteral(resourceName: "mothersDayThumbnail"))
    ]
    
    static var allMissions = [
        Mission(id: 0, charityReferenceId: 141, goalAmount: 2000000, description: "Hurricane Michael's powerful winds and torrential rains damaged homes, businesses, and hospitals. Moving towards communities in Georgia, North and South Carolina, Tropical Storm Michael has left hundreds of thousands of residents without power. That's where we come in - with your help, we will be able to provide aid for countless families in need.", startDate: "Oct 15, 2018"),
        Mission(id: 1, charityReferenceId: 42, goalAmount: 1000000, description: "Cystic Fibrosis Research, Incorporated (CFRI) is a 501(c)(3) charitable organization founded in 1975, that funds innovative cystic fibrosis (CF) research and offers education, advocacy and psychosocial support programs and services to those with CF, as well as their families and caregivers. We are raising funds in an effort to cure patients of this terrible condition.", startDate: "Oct 15, 2018"),
        Mission(id: 2, charityReferenceId: 5, goalAmount: 800000, description: "The Barbara Bush Foundation for Family Literacy is a non-profit organisation, based in Florida, that seeks to improve literacy in the United States through programs directed towards preschool children and parental literacy. With your help, we will be able to provide supplies for thousands of children who are seeking an education in literature.", startDate: "Oct 15, 2018"),
        Mission(id: 3, charityReferenceId: 34, goalAmount: 2000000, description: "The Environmental and Energy Study Institute (EESI) is an independent, bi-partisan 501(c)(3) non-profit organization that aims to promote environmentally sustainable societies.[1] Based out of Washington, DC, EESI seeks to be a catalyst moving society away from environmentally damaging fossil fuels and toward a clean energy future", startDate: "Oct 15, 2018"),
        Mission(id: 4, charityReferenceId: 76, goalAmount: 2000000, description: "Habitat for Humanity of Collier County is part of a global, nonprofit housing organization operated on Christian principles that seeks to put God’s love into action by building homes, communities and hope. With your donations, we will be able to build 10,000 new homes for families in need and provide them with the resources they need to get on their feet.", startDate: "Oct 15, 2018"),
        Mission(id: 5, charityReferenceId: 88, goalAmount: 2000000, description: "Place of Hope is a unique, faith-based, state-licensed children’s organization providing family-style foster care (emergency and long-term); family outreach and intervention; maternity care; safety for victims of domestic minor sex trafficking; hope and healing opportunities for children and families who have been traumatized by abuse and neglect throughout our region.", startDate: "Oct 15, 2018"),
        Mission(id: 6, charityReferenceId: 133, goalAmount: 2000000, description: "The Wildlife Conservation Network is a United States-based 501 non-profit organization that partners with conservationists from around the world and is dedicated to developing community-based projects that help wildlife and people co-exist. With your donation, we will be able to conserve 10,000 acres of land inhabited by wildlife.", startDate: "Oct 15, 2018")
    ]
}
